jwt:
  secret: "$JWT_SECRET"
  issuer: "$JWT_ISSUER"
  audience: "$JWT_AUDIENCE"
  realm: "$JWT_REALM"

ktor:
  deployment:
    port: 8080
  application:
    modules:
      - com.example.pocketLabs.ApplicationKt.module
